dist: trusty
sudo: required
language: cpp
compiler: g++
before_install:
  - sudo apt-get -qq update  
  - sudo apt-get install -y yasm libav-tools/xenial-updates
script: 
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - g++ --version
  - make
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

