language: cpp
compiler: gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install libopenal-dev 
  - sudo apt-get install libavformat-dev
  - sudo apt-get install libalut-dev 
  - sudo apt-get install libavcodec-dev
  - sudo apt-get install libavutil-dev
  - sudo apt-get install libswscale-dev
  - sudo apt-get install libavfilter-dev
script: make
