language: cpp
compiler: gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install ffmpeg libopenal-dev libalut-dev libavformat-dev libavcodec-dev libavutil-dev libswscale-dev libswresample-dev libavfilter-dev
script: make
