language: cpp
compiler: gcc
before_install:
  - sudo apt-get install ffmpeg
  - sudo apt-get install libavformat-dev
  - sudo apt-get install libavcodec-dev
  - sudo apt-get install libavutil-dev
  - sudo apt-get install libswscale-dev
  - sudo apt-get install libavfilter-dev
script: make
