DSVSCA:
	g++ main.cpp "input/decomposer.cpp" -lavformat -lavcodec -lavfilter -lavutil -lpthread -lswresample -lswscale -o DSVSCA

debug:
	g++ -g main.cpp "input/decomposer.cpp" -lavformat -lavcodec -lavfilter -lavutil -lpthread -lswresample -lswscale -o DSVSCA_debug
